### ISSUE TITLE
请问下系统版本是多少的？

### ISSUE THREAD

**Issue by kl79613** [xxy6910/EFI_OC0.9.1_Z790M_13700k_6600XT#1]
请问下系统版本是多少的？
Ventura 13.3.0和13.3.1的版本都能用吗？

**Comment by xxy6910** [comment]
都可以用，小版本无所谓，Ventura13.0 - Ventura13.3.1都可以

**Comment by kl79613** [comment]
> 都可以用，小版本无所谓，Ventura13.0 - Ventura13.3.1都可以

多谢
